// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gRPC_Generated/Protos_Generated/getReservation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from gRPC_Generated/Protos_Generated/getReservation.proto</summary>
public static partial class GetReservationReflection {

  #region Descriptor
  /// <summary>File descriptor for gRPC_Generated/Protos_Generated/getReservation.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetReservationReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiBnUlBDL1Byb3Rvcy9nZXRSZXNlcnZhdGlvbi5wcm90bxofZ29vZ2xlL3By",
          "b3RvYnVmL3RpbWVzdGFtcC5wcm90byIgChJSZXNlcnZhdGlvblJlcXVlc3QS",
          "CgoCaWQYASABKAUi5QEKE1Jlc2VydmF0aW9uUmVzcG9uc2USFgoOcmVzZXJ2",
          "YXRpb25faWQYASABKAUSEwoLY3VzdG9tZXJfaWQYAiABKAUSFQoNY3VzdG9t",
          "ZXJfbmFtZRgDIAEoCRIVCg1yZXN0YXVyYW50X2lkGAQgASgFEhcKD3Jlc3Rh",
          "dXJhbnRfbmFtZRgFIAEoCRIQCgh0YWJsZV9pZBgGIAEoBRI0ChByZXNlcnZh",
          "dGlvbl9kYXRlGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIS",
          "CgpwYXJ0eV9zaXplGAggASgFMlEKDlJlc2VydmF0aW9uUnBjEj8KEkdldFJl",
          "c2VydmF0aW9uQnlJZBITLlJlc2VydmF0aW9uUmVxdWVzdBoULlJlc2VydmF0",
          "aW9uUmVzcG9uc2ViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ReservationRequest), global::ReservationRequest.Parser, new[]{ "Id" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ReservationResponse), global::ReservationResponse.Parser, new[]{ "ReservationId", "CustomerId", "CustomerName", "RestaurantId", "RestaurantName", "TableId", "ReservationDate", "PartySize" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ReservationRequest : pb::IMessage<ReservationRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ReservationRequest> _parser = new pb::MessageParser<ReservationRequest>(() => new ReservationRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ReservationRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetReservationReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationRequest(ReservationRequest other) : this() {
    id_ = other.id_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationRequest Clone() {
    return new ReservationRequest(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ReservationRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ReservationRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ReservationRequest other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ReservationResponse : pb::IMessage<ReservationResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ReservationResponse> _parser = new pb::MessageParser<ReservationResponse>(() => new ReservationResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ReservationResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetReservationReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationResponse(ReservationResponse other) : this() {
    reservationId_ = other.reservationId_;
    customerId_ = other.customerId_;
    customerName_ = other.customerName_;
    restaurantId_ = other.restaurantId_;
    restaurantName_ = other.restaurantName_;
    tableId_ = other.tableId_;
    reservationDate_ = other.reservationDate_ != null ? other.reservationDate_.Clone() : null;
    partySize_ = other.partySize_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationResponse Clone() {
    return new ReservationResponse(this);
  }

  /// <summary>Field number for the "reservation_id" field.</summary>
  public const int ReservationIdFieldNumber = 1;
  private int reservationId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ReservationId {
    get { return reservationId_; }
    set {
      reservationId_ = value;
    }
  }

  /// <summary>Field number for the "customer_id" field.</summary>
  public const int CustomerIdFieldNumber = 2;
  private int customerId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CustomerId {
    get { return customerId_; }
    set {
      customerId_ = value;
    }
  }

  /// <summary>Field number for the "customer_name" field.</summary>
  public const int CustomerNameFieldNumber = 3;
  private string customerName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CustomerName {
    get { return customerName_; }
    set {
      customerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "restaurant_id" field.</summary>
  public const int RestaurantIdFieldNumber = 4;
  private int restaurantId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RestaurantId {
    get { return restaurantId_; }
    set {
      restaurantId_ = value;
    }
  }

  /// <summary>Field number for the "restaurant_name" field.</summary>
  public const int RestaurantNameFieldNumber = 5;
  private string restaurantName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RestaurantName {
    get { return restaurantName_; }
    set {
      restaurantName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "table_id" field.</summary>
  public const int TableIdFieldNumber = 6;
  private int tableId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TableId {
    get { return tableId_; }
    set {
      tableId_ = value;
    }
  }

  /// <summary>Field number for the "reservation_date" field.</summary>
  public const int ReservationDateFieldNumber = 7;
  private global::Google.Protobuf.WellKnownTypes.Timestamp reservationDate_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp ReservationDate {
    get { return reservationDate_; }
    set {
      reservationDate_ = value;
    }
  }

  /// <summary>Field number for the "party_size" field.</summary>
  public const int PartySizeFieldNumber = 8;
  private int partySize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PartySize {
    get { return partySize_; }
    set {
      partySize_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ReservationResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ReservationResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ReservationId != other.ReservationId) return false;
    if (CustomerId != other.CustomerId) return false;
    if (CustomerName != other.CustomerName) return false;
    if (RestaurantId != other.RestaurantId) return false;
    if (RestaurantName != other.RestaurantName) return false;
    if (TableId != other.TableId) return false;
    if (!object.Equals(ReservationDate, other.ReservationDate)) return false;
    if (PartySize != other.PartySize) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ReservationId != 0) hash ^= ReservationId.GetHashCode();
    if (CustomerId != 0) hash ^= CustomerId.GetHashCode();
    if (CustomerName.Length != 0) hash ^= CustomerName.GetHashCode();
    if (RestaurantId != 0) hash ^= RestaurantId.GetHashCode();
    if (RestaurantName.Length != 0) hash ^= RestaurantName.GetHashCode();
    if (TableId != 0) hash ^= TableId.GetHashCode();
    if (reservationDate_ != null) hash ^= ReservationDate.GetHashCode();
    if (PartySize != 0) hash ^= PartySize.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ReservationId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ReservationId);
    }
    if (CustomerId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CustomerId);
    }
    if (CustomerName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(CustomerName);
    }
    if (RestaurantId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(RestaurantId);
    }
    if (RestaurantName.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RestaurantName);
    }
    if (TableId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TableId);
    }
    if (reservationDate_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(ReservationDate);
    }
    if (PartySize != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(PartySize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ReservationId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ReservationId);
    }
    if (CustomerId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CustomerId);
    }
    if (CustomerName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(CustomerName);
    }
    if (RestaurantId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(RestaurantId);
    }
    if (RestaurantName.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RestaurantName);
    }
    if (TableId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TableId);
    }
    if (reservationDate_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(ReservationDate);
    }
    if (PartySize != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(PartySize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ReservationId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReservationId);
    }
    if (CustomerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CustomerId);
    }
    if (CustomerName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomerName);
    }
    if (RestaurantId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RestaurantId);
    }
    if (RestaurantName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RestaurantName);
    }
    if (TableId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TableId);
    }
    if (reservationDate_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReservationDate);
    }
    if (PartySize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PartySize);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ReservationResponse other) {
    if (other == null) {
      return;
    }
    if (other.ReservationId != 0) {
      ReservationId = other.ReservationId;
    }
    if (other.CustomerId != 0) {
      CustomerId = other.CustomerId;
    }
    if (other.CustomerName.Length != 0) {
      CustomerName = other.CustomerName;
    }
    if (other.RestaurantId != 0) {
      RestaurantId = other.RestaurantId;
    }
    if (other.RestaurantName.Length != 0) {
      RestaurantName = other.RestaurantName;
    }
    if (other.TableId != 0) {
      TableId = other.TableId;
    }
    if (other.reservationDate_ != null) {
      if (reservationDate_ == null) {
        ReservationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      ReservationDate.MergeFrom(other.ReservationDate);
    }
    if (other.PartySize != 0) {
      PartySize = other.PartySize;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ReservationId = input.ReadInt32();
          break;
        }
        case 16: {
          CustomerId = input.ReadInt32();
          break;
        }
        case 26: {
          CustomerName = input.ReadString();
          break;
        }
        case 32: {
          RestaurantId = input.ReadInt32();
          break;
        }
        case 42: {
          RestaurantName = input.ReadString();
          break;
        }
        case 48: {
          TableId = input.ReadInt32();
          break;
        }
        case 58: {
          if (reservationDate_ == null) {
            ReservationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(ReservationDate);
          break;
        }
        case 64: {
          PartySize = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ReservationId = input.ReadInt32();
          break;
        }
        case 16: {
          CustomerId = input.ReadInt32();
          break;
        }
        case 26: {
          CustomerName = input.ReadString();
          break;
        }
        case 32: {
          RestaurantId = input.ReadInt32();
          break;
        }
        case 42: {
          RestaurantName = input.ReadString();
          break;
        }
        case 48: {
          TableId = input.ReadInt32();
          break;
        }
        case 58: {
          if (reservationDate_ == null) {
            ReservationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(ReservationDate);
          break;
        }
        case 64: {
          PartySize = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
